# Self elevate
If (!([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] "Administrator")) {
	Start-Process powershell.exe "-NoProfile -ExecutionPolicy Bypass -File `"$PSCommandPath`"" -Verb RunAs;
	Exit
}

Import-Module –Name $PSScriptRoot\modules\Win10

# (New-Object System.Net.WebClient).DownloadString("https://raw.githubusercontent.com/fpanhan/windows-setup/main/modules\Win10.psm1")

$tweaks = @(
    @{name = "DisableTelemetry"},
	@{name = "DisableUWPBackgroundApps"},
	@{name = "EnableUpdateMSProducts"},
	@{name = "DisableUpdateRestart"},
	@{name = "DisableMaintenanceWakeUp"},
	@{name = "DisableSharedExperiences"},
	@{name = "EnableClipboardHistory"},
	@{name = "DisableAutoplay"},
	@{name = "DisableAutorun"},
	@{name = "EnableNTFSLongPaths"},
	@{name = "DisableHibernation"},
	@{name = "EnableFastStartup"},
	@{name = "DisableActionCenter"},
	@{name = "HideNetworkFromLockScreen"},
	@{name = "ShowShutdownOnLockScreen"},
	@{name = "DisableLockScreenBlur"},
	@{name = "DisableAccessibilityKeys"},
	@{name = "ShowTaskManagerDetails"},
	@{name = "ShowFileOperationsDetails"},
	@{name = "HideTaskbarSearch"},
	@{name = "ShowSmallTaskbarIcons"},
	@{name = "HideTaskView"},
	@{name = "SetTaskbarCombineWhenFull"},
	@{name = "HideTaskbarPeopleIcon"},
	@{name = "ShowTrayIcons"},
	@{name = "DisableNewAppPrompt"},
	@{name = "HideRecentlyAddedApps"},
	@{name = "HideMostUsedApps"},
	@{name = "SetControlPanelSmallIcons"},
	@{name = "DisableShortcutInName"},
	@{name = "HideShortcutArrow"},
	@{name = "SetVisualFXPerformance"},
	@{name = "SetAppsDarkMode"},
	@{name = "SetSystemDarkMode"},
	@{name = "DisableStartupSound"},
	@{name = "DisableChangingSoundScheme"},
	@{name = "ShowExplorerTitleFullPath"},
	@{name = "ShowKnownExtensions"},
	@{name = "ShowHiddenFiles"},
	@{name = "EnableNavPaneExpand"},
	@{name = "ShowNavPaneAllFolders"},
	@{name = "HideSelectCheckboxes"},
	@{name = "HideSyncNotifications"},
	@{name = "HideRecentShortcuts"},
	@{name = "SetExplorerThisPC"},
	@{name = "ShowQuickAccess"},
	@{name = "ShowRecycleBinOnDesktop"},
	@{name = "ShowThisPCOnDesktop"},
	@{name = "ShowDesktopIcons"},
	@{name = "ShowBuildNumberOnDesktop"},
	@{name = "HideDesktopFromThisPC"},
	@{name = "ShowDesktopInExplorer"},
	@{name = "HideDocumentsFromThisPC"},
	@{name = "ShowDocumentsInExplorer"},
	@{name = "HideDownloadsFromThisPC"},
	@{name = "ShowDownloadsInExplorer"},
	@{name = "HideMusicFromThisPC"},
	@{name = "HideMusicFromExplorer"},
	@{name = "HideMusicFromExplorer"},
	@{name = "HidePicturesFromExplorer"},
	@{name = "HideVideosFromThisPC"},
	@{name = "HideVideosFromExplorer"},
	@{name = "Hide3DObjectsFromThisPC"},
	@{name = "Hide3DObjectsFromExplorer"},
	@{name = "HideIncludeInLibraryMenu"},
	@{name = "EnableThumbnails"},
	@{name = "EnableThumbnailCache"},
	@{name = "DisableThumbsDBOnNetwork"},
	@{name = "DisableOneDrive"},
	@{name = "UninstallOneDrive"},
	@{name = "UninstallMsftBloat"},
	@{name = "UninstallThirdPartyBloat"},
	@{name = "DisableXboxFeatures"},
	@{name = "DisableAdobeFlash"},
	@{name = "DisableEdgePreload"},
	@{name = "DisableEdgeShortcutCreation"},
	@{name = "DisableIEFirstRun"},
	@{name = "DisableFirstLogonAnimation"},
	@{name = "DisableMediaSharing"},
	@{name = "EnableDeveloperMode"},
	@{name = "UninstallHelloFace"},
	@{name = "InstallPowerShellISE"},
	@{name = "InstallLinuxSubsystem"},
	@{name = "InstallHyperV"},
	@{name = "InstallSSHClient"},
	@{name = "InstallTelnetClient"},
	@{name = "InstallNET23"},
	@{name = "UnsetPhotoViewerAssociation"},
	@{name = "RemovePhotoViewerOpenWith"},
	@{name = "InstallPDFPrinter"},
	@{name = "UninstallXPSPrinter"},
	@{name = "RemoveFaxPrinter"},
	@{name = "UninstallFaxAndScan"},
	@{name = "UnpinStartMenuTiles"},
	@{name = "UnpinTaskbarIcons"}
)

Foreach ($tweak in $tweaks) {
	Invoke-Expression $tweak.name;
}
